### ISSUE TITLE
Implement custom Kryo Serializer for ServiceStats, similar to custom JsonTypeAdapter already created for the same type

### ISSUE THREAD

**Issue by georgechrysanthakopoulos** [dCentralizedSystems/core#10]
the json custom serialize for service stats leads to 10x reduction in serialized size

**Comment by tarlano** [comment]
Nice improvement!

**Comment by georgechrysanthakopoulos** [comment]
needs one more optimization to speed up deserialization: we now record the base time bin key, so we dont have to search for it when deserializing, to re-normalize the time bin absolute time values. This leads to a o(N) speed up when rendering / processing serialized time series. In progress, will be checked in soon
