### ISSUE TITLE
Update to Java11

### ISSUE THREAD

**Issue by PrudviDanda** [dCentralizedSystems/core#22]
Hello , 

When are you planning moving to java 11 ? is there a timeline for the update ?

**Comment by georgechrysanthakopoulos** [comment]
Hi, no timeline, its a risky move for us (we have this runtime deployed across our robots, upgrading to Java11 will mean a massive download over the air).

I would welcome a pull request that does the upgrade though, it will mostly be a lot of maven file changes.. :)
